const DOM = {};
const AppState = { topic: '', side: 'pro', depth: 'standard', context: '', currentContent: '', records: [] };
function initDOM() { DOM.topicInput = document.getElementById('topic-input'); DOM.side = document.getElementById('side'); DOM.depth = document.getElementById('depth'); DOM.context = document.getElementById('context'); DOM.btnGenerate = document.getElementById('btn-generate'); DOM.resultArea = document.getElementById('result-area'); DOM.content = document.getElementById('content'); DOM.historyPanel = document.getElementById('history-panel'); DOM.historyList = document.getElementById('history-list'); DOM.historyOverlay = document.getElementById('history-overlay'); DOM.settingsModal = document.getElementById('settings-modal'); DOM.toast = document.getElementById('toast'); }
function initEvents() {
    DOM.topicInput.addEventListener('input', () => AppState.topic = DOM.topicInput.value);
    DOM.side.addEventListener('change', () => AppState.side = DOM.side.value);
    DOM.depth.addEventListener('change', () => AppState.depth = DOM.depth.value);
    DOM.context.addEventListener('input', () => AppState.context = DOM.context.value);
    DOM.btnGenerate.addEventListener('click', generate);
    document.getElementById('btn-save').addEventListener('click', saveRecord);
    document.getElementById('btn-history').addEventListener('click', () => { DOM.historyPanel.classList.add('open'); DOM.historyOverlay.classList.remove('hidden'); });
    document.getElementById('btn-close-history').addEventListener('click', closeHistory); DOM.historyOverlay.addEventListener('click', closeHistory);
    document.getElementById('btn-settings').addEventListener('click', () => { DOM.settingsModal.classList.add('show'); loadSettings(); });
    document.getElementById('btn-close-settings').addEventListener('click', () => DOM.settingsModal.classList.remove('show'));
    document.getElementById('btn-cancel-settings').addEventListener('click', () => DOM.settingsModal.classList.remove('show'));
    document.getElementById('btn-save-settings').addEventListener('click', saveSettings);
    document.querySelectorAll('.example-btn').forEach(btn => btn.addEventListener('click', () => loadExample(btn.dataset.example)));
}
const EXAMPLES = { ai: { topic: '人工智能是否会取代人类大部分工作？', side: 'both' }, '996': { topic: '996工作制是否应该被禁止？', side: 'both' }, edu: { topic: '应试教育利大于弊还是弊大于利？', side: 'both' }, social: { topic: '社交媒体是否对青少年心理健康有害？', side: 'both' } };
function loadExample(key) { const ex = EXAMPLES[key]; if (!ex) return; DOM.topicInput.value = ex.topic; AppState.topic = ex.topic; DOM.side.value = ex.side; AppState.side = ex.side; showToast('info', '已填入', '点击生成观点'); }
async function generate() { if (!AppState.topic.trim()) { showToast('warning', '请输入辩题', ''); return; } DOM.resultArea.classList.remove('hidden'); DOM.content.innerHTML = ''; AppState.currentContent = ''; await AIService.generate(AppState.topic, AppState.side, AppState.depth, AppState.context, (t) => { AppState.currentContent += t; DOM.content.innerHTML = formatContent(AppState.currentContent); }, () => showToast('success', '观点生成完成', ''), (e) => showToast('error', '生成失败', e.message)); }
function formatContent(text) { return text.replace(/^## ✅(.+)$/gm, '<h2 class="text-xl font-bold text-green-700 mt-5 mb-3">✅$1</h2>').replace(/^## ❌(.+)$/gm, '<h2 class="text-xl font-bold text-red-700 mt-5 mb-3">❌$1</h2>').replace(/^## (.+)$/gm, '<h2 class="text-xl font-bold text-gray-800 mt-5 mb-3">$1</h2>').replace(/^### (.+)$/gm, '<h3 class="text-lg font-semibold text-blue-700 mt-4 mb-2">$1</h3>').replace(/\*\*(.+?)\*\*/g, '<strong class="text-slate-800">$1</strong>').replace(/\n/g, '<br>'); }
async function saveRecord() { if (!AppState.currentContent) { showToast('warning', '无内容', ''); return; } const sideLabels = { pro: '正方', con: '反方', both: '双方' }; const record = { topic: AppState.topic.substring(0, 30) + '...', side: AppState.side, sideLabel: sideLabels[AppState.side], content: AppState.currentContent }; const result = await StorageService.saveRecord(record); if (result.success) { showToast('success', '已保存', ''); loadHistory(); } }
async function loadHistory() { AppState.records = await StorageService.getRecords(); renderHistory(); }
function renderHistory() { if (AppState.records.length === 0) { DOM.historyList.innerHTML = '<p class="text-gray-400 text-sm text-center">暂无记录</p>'; return; } DOM.historyList.innerHTML = AppState.records.map(r => `<div class="p-3 bg-slate-50 rounded-xl"><div class="font-medium text-gray-700 truncate">💬 ${r.topic}</div><div class="text-xs text-gray-400 mt-1">${r.sideLabel} • ${new Date(r.createdAt).toLocaleDateString()}</div></div>`).join(''); }
function closeHistory() { DOM.historyPanel.classList.remove('open'); DOM.historyOverlay.classList.add('hidden'); }
function loadSettings() { const c = AIService.getModelConfig() || {}; document.getElementById('api-url').value = c.apiUrl || ''; document.getElementById('api-key').value = c.apiKey || ''; document.getElementById('model-name').value = c.modelName || ''; }
function saveSettings() { const c = { apiUrl: document.getElementById('api-url').value.trim(), apiKey: document.getElementById('api-key').value.trim(), modelName: document.getElementById('model-name').value.trim() || 'GLM-4-Flash' }; if (!c.apiUrl || !c.apiKey) { showToast('warning', '请填写完整', ''); return; } AIService.saveModelConfig(c); DOM.settingsModal.classList.remove('show'); showToast('success', '配置已保存', ''); }
function showToast(type, title, message) { const icons = { success: '✅', error: '❌', warning: '⚠️', info: 'ℹ️' }; const colors = { success: 'bg-green-500', error: 'bg-red-500', warning: 'bg-yellow-500', info: 'bg-blue-500' }; document.getElementById('toast-icon').className = `w-8 h-8 rounded-full flex items-center justify-center ${colors[type]}`; document.getElementById('toast-icon').textContent = icons[type]; document.getElementById('toast-title').textContent = title; document.getElementById('toast-message').textContent = message; DOM.toast.classList.remove('hidden'); setTimeout(() => DOM.toast.classList.add('hidden'), 3000); }
async function init() { initDOM(); initEvents(); await loadHistory(); const config = await AIService.initConfig(); if (!config) setTimeout(() => { DOM.settingsModal.classList.add('show'); showToast('info', '欢迎使用', '请配置 AI 模型'); }, 500); }
document.addEventListener('DOMContentLoaded', init);
